version: "0.1"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend_container
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
